language: csharp
solution: IsImageUrlDotNet.sln

os:
  - linux
  - osx

mono:
  - latest
  - 4.2.2
  - 4.0.5

install:

before_script:
  - chmod +x travis-autogen.sh

script: ./travis-autogen.sh && make && sudo make install && xbuild ./IsImageUrlDotNet.Test/fsharp-library-unittests-build.proj /p:TargetFramework=net40 /p:Configuration=Release && (cd tests/projects; ./build.sh) && (cd tests/fsharp/core; ./run-opt.sh)

matrix:
  allow_failures:
    - mono: 4.2.2